### ISSUE TITLE
docs: typo in `Input` component page

### ISSUE THREAD

**Issue by Web3NL** [dfinity/gix-components#369]
https://gix.design/components/input

Should be capital letter `Input`

Currently its like an html element input

**Comment by peterpeterparker** [comment]
Well spotted @Web3NL. PR to fix the typo -> #370. Thanks.

**Comment by Web3NL** [comment]
Also noticed that the placeholder doesnt work on its own. It will display undefined if the value attribute isnt set

**Comment by Web3NL** [comment]
Ans name is mandetory, which is missing in the example i believe

**Comment by peterpeterparker** [comment]
The placeholder is mandatory, not sure what you mean.
https://github.com/dfinity/gix-components/blob/18fb76391ed2c109fe89ccd06a49a37e26d26edf/src/lib/components/Input.svelte#L14

**Comment by peterpeterparker** [comment]
We merged the doc typo fix @Web3NL. As I said above, not sure about what you meant with the placeholder. Please do open another issue if I misunderstood something!
